name: bilibili-daily-task

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    - cron: '10 6 * * *'
    # cron表达式，Actions时区是UTC时间，所以要往前推8个小时,如上表示每天14点10分

jobs:
  run-bilibili-tool:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Add GitHub Packages repository
      run: |
        echo "deb [signed-by=/usr/share/keyrings/github-packages-keyring.gpg] https://packages.githubusercontent.com/ubuntu/24.04/prod focal main" | sudo tee -a /etc/apt/sources.list.d/github.list
        curl -L https://packages.githubusercontent.com/ubuntu/24.04/prod/gpgkey | sudo gpg --dearmor -o /usr/share/keyrings/github-packages-keyring.gpg

    - name: Install dependencies
    
      run: dotnet restore
      
    - name: Build
      run: dotnet build --configuration Release --no-restore
      
    - name: Run
      env:
        userId: ${{secrets.USERID}}
        sessData: ${{secrets.SESSDATA}}
        biliJct: ${{secrets.BILIJCT}}
        otherConfigs: ${{secrets.OTHERCONFIGS}}
      run: dotnet run -p ./src/Ray.BiliBiliTool.Console -userId=${userId} -sessData=${sessData} -biliJct=${biliJct} -closeConsoleWhenEnd=1 ${otherConfigs}
