name: bilibili-daily-task

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    - cron: '10 6 * * *'
    # cron表达式，Actions时区是UTC时间，所以要往前推8个小时,如上表示每天14点10分

jobs:
  run-bilibili-tool:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Update package lists
      run: |
        sudo apt-get update
        sudo apt-get update --fix-missing

    - name: Install OpenSSL
      run: |
        sudo apt-get install -y libssl-dev

    - name: Set InvariantGlobalization
      run: echo "DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=1" >> $GITHUB_ENV
      
    - name: Setup .NET 6
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x  # 使用 .NET 6

    - name: Download dotnet-install.sh
      run: |
        curl -L https://dot.net/v1/dotnet-install.sh -o dotnet-install.sh

    - name: Make dotnet-install.sh executable
      run: |
        chmod +x dotnet-install.sh

    - name: Install .NET Core 3.1 Runtime
      run: |
        ./dotnet-install.sh --architecture x64 --install-dir /usr/share/dotnet/ --runtime aspnet --version 3.1.0

    - name: Restore dependencies
      run: dotnet restore

    - name: Update Refit package
      run: dotnet add package Refit --version 6.0.0  # 请使用最新的稳定版本

    - name: Build
      run: dotnet build --configuration Release --no-restore
      
    - name: Run
      env:
        userId: ${{ secrets.USERID }}
        sessData: ${{ secrets.SESSDATA }}
        biliJct: ${{ secrets.BILIJCT }}
        otherConfigs: ${{ secrets.OTHERCONFIGS }}
      run: dotnet run --project ./src/Ray.BiliBiliTool.Console -userId=${userId} -sessData=${sessData} -biliJct=${biliJct} -closeConsoleWhenEnd=1 ${otherConfigs}
